#include <iostream>
#include <memory>
#include <fstream>
#include "ui/WizardManager.hpp"
#include "ui/wizard/CameraSelectionPage.hpp"
#include "ui/wizard/CameraOrientationPage.hpp"
#include "ui/wizard/TableCalibrationPage.hpp"
#include "ui/wizard/TableDimensionsPage.hpp"
#include "ui/wizard/CalibrationCompletePage.hpp"
#include "../../core/util/UserConfig.hpp"

using namespace pv;

void printWelcome() {
    std::cout << "========================================" << std::endl;
    std::cout << "  Pool Vision Setup Wizard" << std::endl;
    std::cout << "========================================" << std::endl;
    std::cout << std::endl;
    std::cout << "This wizard will guide you through setting up:" << std::endl;
    std::cout << "  1. Camera selection" << std::endl;
    std::cout << "  2. Camera orientation" << std::endl;
    std::cout << "  3. Table calibration" << std::endl;
    std::cout << "  4. Table dimensions" << std::endl;
    std::cout << std::endl;
    std::cout << "Press ENTER to begin, or Ctrl+C to cancel..." << std::endl;
    std::cin.get();
}

bool saveConfigurationToUserDirectories(const WizardConfig& config) {
    UserConfig& userConfig = UserConfig::instance();
    
    try {
        // Save camera configuration
        std::ofstream cameraFile(userConfig.getCameraConfigPath());
        if (!cameraFile.is_open()) {
            std::cerr << "Failed to create camera config file" << std::endl;
            return false;
        }
        
        cameraFile << "# Camera Configuration" << std::endl;
        cameraFile << "# Generated by Pool Vision Setup Wizard" << std::endl;
        cameraFile << std::endl;
        cameraFile << "width: " << config.resolution.width << std::endl;
        cameraFile << "height: " << config.resolution.height << std::endl;
        cameraFile << "fps: 30" << std::endl;  // Default FPS
        cameraFile << "device_id: " << config.cameraIndex << std::endl;
        cameraFile << "rotation: " << config.rotation << std::endl;
        cameraFile << "flip_horizontal: " << (config.flipHorizontal ? "true" : "false") << std::endl;
        cameraFile << "flip_vertical: " << (config.flipVertical ? "true" : "false") << std::endl;
        cameraFile.close();
        
        // Save table configuration  
        std::ofstream tableFile(userConfig.getTableConfigPath());
        if (!tableFile.is_open()) {
            std::cerr << "Failed to create table config file" << std::endl;
            return false;
        }
        
        tableFile << "# Table Configuration" << std::endl;
        tableFile << "# Generated by Pool Vision Setup Wizard" << std::endl;
        tableFile << std::endl;
        tableFile << "table_width: " << static_cast<int>(config.tableWidth * 1000) << std::endl;  // Convert to mm
        tableFile << "table_height: " << static_cast<int>(config.tableLength * 1000) << std::endl;  // Convert to mm  
        tableFile << "ball_radius_px: " << config.maxRadius << std::endl;
        tableFile << std::endl;
        
        // Save homography matrix
        tableFile << "# Homography matrix (3x3, row-major)" << std::endl;
        tableFile << "homography: [";
        if (!config.homographyMatrix.empty()) {
            for (int i = 0; i < 9; ++i) {
                if (i > 0) tableFile << ", ";
                tableFile << config.homographyMatrix.at<double>(i/3, i%3);
            }
        } else {
            // Default identity matrix if no homography computed
            tableFile << "1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0";
        }
        tableFile << "]" << std::endl;
        tableFile << std::endl;
        
        // Save pocket positions
        tableFile << "# Pocket positions" << std::endl;
        tableFile << "pockets: [";
        for (size_t i = 0; i < config.pocketPositions.size(); ++i) {
            if (i > 0) tableFile << ", ";
            tableFile << config.pocketPositions[i].x << ", " << config.pocketPositions[i].y;
        }
        tableFile << "]" << std::endl;
        tableFile.close();
        
        // Copy default colors configuration if not already done
        if (!userConfig.copyDefaultConfigs()) {
            std::cerr << "Warning: Could not copy default color configuration" << std::endl;
            // Continue anyway - colors config is less critical
        }
        
        std::cout << "Configuration saved successfully!" << std::endl;
        return true;
        
    } catch (const std::exception& e) {
        std::cerr << "Error saving configuration: " << e.what() << std::endl;
        return false;
    }
}

int main(int argc, char** argv) {
    printWelcome();
    
    try {
        // Initialize user configuration directories
        UserConfig& userConfig = UserConfig::instance();
        if (!userConfig.initializeUserDirectories()) {
            std::cerr << "Failed to initialize user configuration directories" << std::endl;
            return 1;
        }
        
        // Create wizard manager
        WizardManager wizard;
        
        // Add pages in order
        wizard.addPage(std::make_unique<CameraSelectionPage>());
        wizard.addPage(std::make_unique<CameraOrientationPage>());
        wizard.addPage(std::make_unique<TableCalibrationPage>());
        wizard.addPage(std::make_unique<TableDimensionsPage>());
        wizard.addPage(std::make_unique<CalibrationCompletePage>());
        
        // Run wizard
        std::cout << "\nStarting wizard..." << std::endl;
        bool success = wizard.run();
        
        if (success) {
            std::cout << "\n========================================" << std::endl;
            std::cout << "  Setup completed successfully!" << std::endl;
            std::cout << "========================================" << std::endl;
            
            // Save configuration to user directories
            if (saveConfigurationToUserDirectories(wizard.getConfig())) {
                std::cout << "\nConfiguration files have been saved to:" << std::endl;
                std::cout << "  " << userConfig.getUserConfigDir() << std::endl;
                
                // Create default settings
                userConfig.createDefaultSettings();
                
                // Mark setup as complete
                userConfig.markConfigured();
                
                std::cout << "\nYou can now run: pool_vision.exe" << std::endl;
                std::cout << std::endl;
                return 0;
            } else {
                std::cerr << "Failed to save configuration files" << std::endl;
                return 1;
            }
        } else {
            std::cout << "\nSetup cancelled by user." << std::endl;
            return 1;
        }
    }
    catch (const std::exception& e) {
        std::cerr << "Error: " << e.what() << std::endl;
        return 1;
    }
    catch (...) {
        std::cerr << "Unknown error occurred" << std::endl;
        return 1;
    }
}
